export const GET_ALL_ASSIGNMENTS_SUCCESS = "GET_ALL_ASSIGNMENTS_SUCCESS";
export const GET_ALL_ASSIGNMENTS_START = "GET_ALL_ASSIGNMENTS_START";
export const GET_ALL_ASSIGNMENTS_FAIL = "GET_ALL_ASSIGNMENTS_FAIL";

export const SET_HEADER_NAME = "SET_HEADER_NAME";

export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_START = "SIGNIN_USER_START";
export const SIGNIN_USER_FAIL = "SIGNIN_USER_FAIL";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const SIGNOUT_USER_FAIL = "SIGNOUT_USER_FAIL";


